In [1]:
import os
import numpy as np
import pandas as pd
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.io as pio

In [2]:
__author__ = 'Aleksandar Anžel'
__copyright__ = ''
__credits__ = ['Aleksandar Anžel', 'Vincent Schilling']
__license__ = 'GNU General Public License v3.0'
__version__ = '1.0'
__maintainer__ = 'Aleksandar Anžel'
__email__ = 'AnzelA@rki.de'
__status__ = 'Dev'

In [3]:
_PATH_ROOT_DATA = os.path.join('..', 'Data', 'Summarized_Data_for_vis')
_PATH_DIA_DIR = os.path.join(_PATH_ROOT_DATA, 'dia_data')
_PATH_DDA_DIR = os.path.join(_PATH_ROOT_DATA, 'dda_data')

_PATH_ROOT_RESULTS = os.path.join('..', 'Data', 'Results')
_PATH_RESULTS_DDA = os.path.join(_PATH_ROOT_RESULTS, 'DDA')
_PATH_RESULTS_DIA = os.path.join(_PATH_ROOT_RESULTS, 'DIA')
_PATH_RESULTS_DDA_PDF = os.path.join(_PATH_ROOT_RESULTS, 'DDA', 'PDF')
_PATH_RESULTS_DIA_PDF = os.path.join(_PATH_ROOT_RESULTS, 'DIA', 'PDF')
_PATH_RESULTS_DDA_HTML = os.path.join(_PATH_ROOT_RESULTS, 'DDA', 'HTML')
_PATH_RESULTS_DIA_HTML = os.path.join(_PATH_ROOT_RESULTS, 'DIA', 'HTML')

for path_tmp in [_PATH_RESULTS_DDA_PDF, _PATH_RESULTS_DIA_PDF,
                 _PATH_RESULTS_DDA_HTML, _PATH_RESULTS_DIA_HTML]:
    os.makedirs(path_tmp, exist_ok=True)


_PATH_DDA_RUN = os.path.join(_PATH_DDA_DIR, 'qc_merged_100SPD_ddaPASEF.tsv')
_PATH_DIA_100SPD = os.path.join(_PATH_DIA_DIR, '100SPD_DIA_merged_stats.tsv')
_PATH_DIA_200SPD = os.path.join(_PATH_DIA_DIR, '200SPD_DIA_merged_stats.tsv')
_PATH_DIA_500SPD = os.path.join(_PATH_DIA_DIR, '500SPD_DIA_merged_stats.tsv')
_PATH_DIA_ALL_RUNS = os.path.join(_PATH_DIA_DIR, 'all_runs_merged_stats.tsv')

In [4]:
_STRING_COLOR_BLUE = '#6495ed'
_STRING_COLOR_DARK_GREY = '#636363'
_STRING_COLOR_DIA100SPD = '#66c2a5'
_STRING_COLOR_DIA100SPD_STRONG = '#3b6759'
_STRING_COLOR_DIA200SPD = '#fc8d62'
_STRING_COLOR_DIA200SPD_STRONG = '#854d37'
_STRING_COLOR_DIA500SPD = '#8da0cb'
_STRING_COLOR_DIA500SPD_STRONG = '#4d566b'
_STRING_COLOR_DIAall = '#e78ac3'
_STRING_COLOR_DIAall_STRONG = '#7a4c67'

pio.templates.default = "simple_white"

## DDA Analysis --- Brief Dataset Inspection

In [5]:
df_dda = pd.read_csv(_PATH_DDA_RUN, delimiter='\t')
df_dda.head(20)

,sample_id,Identified_proteins,Identified_peptides,Median_precursor_mass_error_ppm,Median_precursor_mass_error_ppm_signed,Pct_charge_2plus,Pct_charge_3plus,Pct_zero_missed_cleavages,Identified_precursors,Median_RT_FWHM,Median_IM_FWHM,MS1_TIC_median,MS1_TIC_CV,MS2_precursor_events,MS1_frames,MS2_frames,Gradient_min,Total.Protein.Number.Ref,MS1_TIC_CV_pct,Protein.Identification.Rate
0,001_Achromobacter_xylosoxidans_HST_62_DDA100_5422,1651,8453,1.450804,0.000000,68.814815,27.511111,88.925926,10081,5.863,0.018,2080260.0,1.062843,37560,993,5370,11.498185,6134,106.284273,26.915553
1,002_Achromobacter_xylosoxidans_ssp_xylosoxidan...,2010,8854,1.525313,0.000000,70.309680,25.972713,88.897712,10568,5.863,0.018,1162835.0,1.097581,38618,1029,5324,11.497422,6134,109.758106,32.768177
2,003_Acinetobacter_baumannii_DSM30011_DDA100_5340,1436,9367,1.382366,0.104333,73.324863,23.030627,89.079845,11113,5.863,0.020,5986983.0,0.999339,39800,940,5435,11.496826,3765,99.933922,38.140770
3,004_Aeromonas_hydrophila_ssp_hydrophila_DSM301...,1775,11284,1.307438,0.000000,66.057598,29.497109,89.484019,13685,5.863,0.018,1523139.5,1.075307,35505,996,5366,11.497923,4121,107.530743,43.072070
4,005_Acinetobacter_lwoffii_DSM2403_DDA100_4346,1398,8893,1.468724,0.067925,66.673113,28.866112,88.583768,11062,5.863,0.020,4169587.5,1.029494,38418,970,5399,11.497020,3273,102.949405,42.713107
5,007_Acinetobacter_pittii_DSM9312_DDA100_4316,1557,9937,1.376364,0.000000,64.993711,30.358747,89.746661,12238,5.863,0.018,3909090.0,1.011085,36388,951,5424,11.498003,4014,101.108467,38.789238
6,008_Acinetobacter_pittii_DSM9318_DDA100_4382,1563,9284,1.552248,0.000000,70.538079,25.327821,88.043408,11367,5.863,0.020,6973003.5,0.986070,42228,950,5423,11.497300,4014,98.607048,38.938714
7,011_Aeromonas_hydrophila_ssp_hydrophila_DSM301...,1794,10961,1.479291,0.000000,71.757527,23.804041,89.004663,13159,5.863,0.020,5357293.0,1.029362,39914,958,5417,11.497283,4121,102.936176,43.533123
8,012_Aeromonas_hydrophila_ssp_ranae_DSM17695_DD...,1643,9415,1.511074,0.063537,71.338292,24.376275,89.849253,11355,5.863,0.018,934395.5,1.092335,38903,1030,5325,11.496892,4121,109.233527,39.868964
9,013_Aeromonas_veronii_DSM7386_DDA100_4342,1646,8864,1.600373,0.062939,71.978136,23.822044,87.123781,10775,5.863,0.020,2552098.0,1.048124,41369,1009,5349,11.496669,4109,104.812427,40.058408
10,014_Bacillus_atrophaeus_LSSC3_DDA100_5386,1119,4624,1.533899,0.107414,72.091292,24.770528,88.055073,5597,5.863,0.020,1893010.0,1.071840,38871,1002,5357,11.496923,4260,107.184035,26.267606
11,016_Bacillus_cereus_ATCC10987_DDA100_5362,1490,8004,1.491718,0.000000,70.613471,25.661376,87.351637,9794,5.863,0.020,785994.5,1.085999,39129,1024,5331,11.498255,5240,108.599890,28.435115
12,018_Bacillus_atrophaeus_GBSC56_DDA100_5358,1202,4689,1.557195,0.178713,72.754107,24.204312,88.103183,5639,5.863,0.020,3156682.0,1.068837,40322,997,5364,11.497117,4260,106.883688,28.215962
13,019_Bacillus_atrophaeus_NMTD54_DDA100_5348,1261,4716,1.610090,0.092451,73.201958,23.383959,87.347810,5673,5.863,0.020,563971.0,1.100060,41054,1039,5312,11.498159,4260,110.006048,29.600939
14,020_Bacillus_atrophaeus_TS1_DDA100_5378,990,3972,1.424674,0.166024,71.951035,25.132235,88.816684,4762,5.863,0.020,754654.5,1.089432,38613,1022,5335,11.497581,4260,108.943228,23.239437
15,021_Alcaligenes_faecalis_ssp_faecalis_DSM30030...,1606,9419,1.560313,0.000000,68.771066,27.100078,89.007000,11502,5.863,0.018,1227486.0,1.088595,38268,1017,5336,11.497379,3770,108.859471,42.599469
16,022_Alcaligenes_faecalis_ssp_parafaecalis_DSM1...,1395,7645,1.536876,0.085316,68.193860,27.871279,89.364189,9387,5.863,0.018,1634154.0,1.076465,38269,1006,5365,11.498027,3770,107.646509,37.002653
17,023_Citrobacter_amalonaticus_04-08695_DDA100_6488,1480,7090,1.462926,0.000000,75.578714,21.457248,85.811907,8414,5.863,0.020,1020676.0,1.095565,40234,1067,5305,11.497912,5139,109.556500,28.799377
18,024_Bacillus_cereus_DSM31_DDA100_5324,1657,10533,1.467493,0.070338,68.203168,27.646095,87.061715,12993,5.863,0.020,605628.0,1.108069,37750,1029,5325,11.498422,5240,110.806913,31.622137
19,026_Bacillus_halotolerans_LNXM37_DDA100_5346,1699,10528,1.603086,0.000000,71.330870,24.692516,86.751972,12910,5.863,0.020,5662884.0,1.028102,41591,973,5396,11.497720,4109,102.810191,41.348260

In [6]:
df_dda['short_sample_id'] = df_dda['sample_id'].apply(lambda x: '_'.join(x.split('_')[1:-2]))
df_dda

,sample_id,Identified_proteins,Identified_peptides,Median_precursor_mass_error_ppm,Median_precursor_mass_error_ppm_signed,Pct_charge_2plus,Pct_charge_3plus,Pct_zero_missed_cleavages,Identified_precursors,Median_RT_FWHM,...,MS1_TIC_median,MS1_TIC_CV,MS2_precursor_events,MS1_frames,MS2_frames,Gradient_min,Total.Protein.Number.Ref,MS1_TIC_CV_pct,Protein.Identification.Rate,short_sample_id
0,001_Achromobacter_xylosoxidans_HST_62_DDA100_5422,1651,8453,1.450804,0.000000,68.814815,27.511111,88.925926,10081,5.863,...,2080260.0,1.062843,37560,993,5370,11.498185,6134,106.284273,26.915553,Achromobacter_xylosoxidans_HST_62
1,002_Achromobacter_xylosoxidans_ssp_xylosoxidan...,2010,8854,1.525313,0.000000,70.309680,25.972713,88.897712,10568,5.863,...,1162835.0,1.097581,38618,1029,5324,11.497422,6134,109.758106,32.768177,Achromobacter_xylosoxidans_ssp_xylosoxidans_DS...
2,003_Acinetobacter_baumannii_DSM30011_DDA100_5340,1436,9367,1.382366,0.104333,73.324863,23.030627,89.079845,11113,5.863,...,5986983.0,0.999339,39800,940,5435,11.496826,3765,99.933922,38.140770,Acinetobacter_baumannii_DSM30011
3,004_Aeromonas_hydrophila_ssp_hydrophila_DSM301...,1775,11284,1.307438,0.000000,66.057598,29.497109,89.484019,13685,5.863,...,1523139.5,1.075307,35505,996,5366,11.497923,4121,107.530743,43.072070,Aeromonas_hydrophila_ssp_hydrophila_DSM30183
4,005_Acinetobacter_lwoffii_DSM2403_DDA100_4346,1398,8893,1.468724,0.067925,66.673113,28.866112,88.583768,11062,5.863,...,4169587.5,1.029494,38418,970,5399,11.497020,3273,102.949405,42.713107,Acinetobacter_lwoffii_DSM2403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,280_Sphingomonas_paucimobilis_DSM30198_DDA100_...,1880,11033,1.476909,0.000000,71.089440,25.405405,88.219560,13210,5.863,...,5416711.0,1.036251,41911,981,5385,11.497219,4127,103.625057,45.553671,Sphingomonas_paucimobilis_DSM30198
195,281_Staphylococcus_capitis_ssp_capitis_DSM2032...,1002,6494,1.298923,0.101362,71.375599,24.780682,88.287962,7807,5.863,...,3549167.5,1.038040,35881,948,5427,11.497086,2537,103.804006,39.495467,Staphylococcus_capitis_ssp_capitis_DSM20326
196,282_Staphylococcus_capitis_ssp_urealyticus_DSM...,1117,8053,1.245544,0.051385,62.231211,32.793982,84.011071,9922,5.863,...,2679171.0,1.030385,32528,968,5404,11.497967,2537,103.038501,44.028380,Staphylococcus_capitis_ssp_urealyticus_DSM6717
197,283_Staphylococcus_pasteuri_DSM10656_DDA100_4410,927,5306,1.415428,0.090254,66.373557,29.007310,84.659392,6536,5.863,...,3395047.0,1.056687,37052,977,5390,11.497632,2545,105.668727,36.424361,Staphylococcus_pasteuri_DSM10656
198,284_Staphylococcus_pasteuri_DSM10657_DDA100_4416,850,4343,1.163298,0.087448,63.772086,32.146281,86.481304,5166,5.863,...,843081.0,1.080322,29569,1022,5333,11.496942,2545,108.032240,33.398821,Staphylococcus_pasteuri_DSM10657

In [7]:
df_dda.columns

Index(['sample_id', 'Identified_proteins', 'Identified_peptides',
       'Median_precursor_mass_error_ppm',
       'Median_precursor_mass_error_ppm_signed', 'Pct_charge_2plus',
       'Pct_charge_3plus', 'Pct_zero_missed_cleavages',
       'Identified_precursors', 'Median_RT_FWHM', 'Median_IM_FWHM',
       'MS1_TIC_median', 'MS1_TIC_CV', 'MS2_precursor_events', 'MS1_frames',
       'MS2_frames', 'Gradient_min', 'Total.Protein.Number.Ref',
       'MS1_TIC_CV_pct', 'Protein.Identification.Rate', 'short_sample_id'],
      dtype='object')

## DDA --- Visualization

TODO:

* Identified proteins
* Identified peptides
* Protein identification rate (identified vs. reference)
* Median precursor mass error (ppm)
* MS1 TIC CV (%)
* Percentage of zero missed cleavages
* Median RT FWHM
* Median IM FWHM

In [8]:
dict_dda_charts = {
    'Proteins_Identified': {
        'Column_Name': 'Identified_proteins',
        'Charts': None
    },
    'Peptides_Identified': {
        'Column_Name': 'Identified_peptides',
        'Charts': None
    },
    'Protein_Identification_Rate': {
        'Column_Name': 'Protein.Identification.Rate',
        'Charts': None
    },
    'Median_Precursor_Mass_Error (ppm)': {
        'Column_Name': 'Median_precursor_mass_error_ppm',
        'Charts': None
    },
    'MS1_TIC_median': {
        'Column_Name': 'MS1_TIC_median',
        'Charts': None
    },
    'Percentage_of_Zero_Missed_Cleavages': {
        'Column_Name': 'Pct_zero_missed_cleavages',
        'Charts': None
    },
    'Percentage_of_Zero_Missed_Cleavages': {
        'Column_Name': 'Pct_zero_missed_cleavages',
        'Charts': None
    },
    'Median_RT_FWHM': {
        'Column_Name': 'Median_RT_FWHM',
        'Charts': None
    },
    'Median_IM_FWHM': {
        'Column_Name': 'Median_IM_FWHM',
        'Charts': None
    },
}

In [9]:
for string_feature in dict_dda_charts.keys():
    print(string_feature)

    chart_dda = go.Figure()

    chart_dda.add_trace(
        go.Violin(
            x=["value"] * len(df_dda),
            y=df_dda[dict_dda_charts[string_feature]["Column_Name"]],
            name=dict_dda_charts[string_feature]["Column_Name"],
            box_visible=True,
            points="all",
            line_color=_STRING_COLOR_DARK_GREY,
            marker_color=_STRING_COLOR_DARK_GREY
        )
    )

    chart_dda.update_xaxes(
        showticklabels=False, ticks="", showline=True)
    chart_dda.update_yaxes(title=dict(text=string_feature, font=dict(size=30)),
    tickfont=dict(size=25), showgrid=True)
    chart_dda.update_layout(margin=dict(l=80, r=20, t=20, b=80))

    chart_dda.write_image(
        os.path.join(
            _PATH_RESULTS_DDA_PDF,
            "DDA_" + string_feature + ".pdf"))
    chart_dda.write_html(
        os.path.join(
            _PATH_RESULTS_DDA_HTML,
            "DDA_" + string_feature + ".html"))

    dict_dda_charts[string_feature]["Charts"] = chart_dda

Proteins_Identified
Peptides_Identified
Protein_Identification_Rate
Median_Precursor_Mass_Error (ppm)
MS1_TIC_median
Percentage_of_Zero_Missed_Cleavages
Median_RT_FWHM
Median_IM_FWHM

## DIA 100SPD --- Brief Dataset Inspection

In [10]:
df_dia_100SPD = pd.read_csv(_PATH_DIA_100SPD, delimiter='\t')
df_dia_100SPD

,File.Name,Precursors.Identified,Proteins.Identified,Total.Quantity,MS1.Signal,MS2.Signal,FWHM.Scans,FWHM.RT,Median.Mass.Acc.MS1,Median.Mass.Acc.MS1.Corrected,...,Root,Peptides.Identified,Organism,Taxonomic ID (NCBI),Database,Proteome_ID,Strain_ID_Experiment,Strain_ID_UniProt,Total.Protein.Number.Ref,Protein.Identification.Rate
0,/local/job_21726735/Probe 1-96_100SPD_diaPASEF...,20762,2559,1.256380e+09,19667952042,566690077074,2.416,0.038,1.69290,1.59048,...,Probe 1-96_100SPD_diaPASEF_diann_res,17486,Achromobacter xylosoxidans_ssp_xylosoxidans,85698,UniProt,UP000060602,DSM 2402,FDAARGOS_147,6134,41.718291
1,/local/job_21726735/Probe 1-96_100SPD_diaPASEF...,19531,1712,1.194070e+09,18922092432,500496673132,2.311,0.036,1.89482,1.56277,...,Probe 1-96_100SPD_diaPASEF_diann_res,15879,Acinetobacter lwoffii,28090,UniProt,UP000293391,DSM 2403,AL_065,3273,52.306752
2,/local/job_21726735/Probe 1-96_100SPD_diaPASEF...,22673,2066,1.009580e+09,16174142351,392003525604,2.301,0.036,1.58284,1.41112,...,Probe 1-96_100SPD_diaPASEF_diann_res,18652,Acinetobacter pittii,48296,UniProt,UP000271320,DSM 9312(T),TG41884,4014,51.469856
3,/local/job_21726735/Probe 1-96_100SPD_diaPASEF...,22533,2077,1.488530e+09,22920686092,717155923208,2.273,0.035,2.59134,1.59296,...,Probe 1-96_100SPD_diaPASEF_diann_res,18052,Acinetobacter pittii,48296,UniProt,UP000271320,DSM 9318,TG41884,4014,51.743896
4,/local/job_21726735/Probe 1-96_100SPD_diaPASEF...,32575,2776,1.671820e+09,20534690701,604649188736,2.288,0.036,2.01101,1.55412,...,Probe 1-96_100SPD_diaPASEF_diann_res,26793,Aeromonas hydrophila_ssp_hydrophila,196023,UniProt,UP000000756,DSM 30187(T),DSM 30187,4121,67.362291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,/local/job_21726489/Probe 193-206_100SPD_diaPA...,34154,3250,1.500520e+09,18094996158,486152187508,2.256,0.035,2.30862,1.53473,...,Probe 193-206_100SPD_diaPASEF_diann_res,28486,Pseudomonas aeruginosa,287,UniProt,UP000002438,ATCC 33355,DSM 22644,5563,58.421715
195,/local/job_21726489/Probe 193-206_100SPD_diaPA...,16351,1805,1.018850e+09,17805724019,472128157700,2.208,0.034,1.92374,1.37783,...,Probe 193-206_100SPD_diaPASEF_diann_res,13418,Ralstonia condita,329,UniProt,UP000441032,HST 2644,PSLESD1,4773,37.816887
196,/local/job_21726489/Probe 193-206_100SPD_diaPA...,27460,2345,1.537570e+09,18859969131,524771543100,2.217,0.034,1.86010,1.53479,...,Probe 193-206_100SPD_diaPASEF_diann_res,22351,Yersinia enterocolitica,630,UniProt,UP000000642,DSM 11503,NCTC 13174 / 8081,4026,58.246398
197,/local/job_21726489/Probe 193-206_100SPD_diaPA...,31536,2403,1.549310e+09,18806591950,523165624736,2.142,0.033,2.29368,1.48260,...,Probe 193-206_100SPD_diaPASEF_diann_res,25561,Acinetobacter baumannii,470,UniProt,UP000005740,DSM 30007,DSM 30007,3765,63.824701
198,/local/job_21726489/Probe 193-206_100SPD_diaPA...,25803,2134,1.506910e+09,19096000294,537805090172,2.221,0.035,2.32904,1.55417,...,Probe 193-206_100SPD_diaPASEF_diann_res,20716,Acinetobacter baumannii,470,UniProt,UP000005740,DSM 24110,DSM 30007,3765,56.679947

In [11]:
df_dia_100SPD.columns

Index(['File.Name', 'Precursors.Identified', 'Proteins.Identified',
       'Total.Quantity', 'MS1.Signal', 'MS2.Signal', 'FWHM.Scans', 'FWHM.RT',
       'Median.Mass.Acc.MS1', 'Median.Mass.Acc.MS1.Corrected',
       'Median.Mass.Acc.MS2', 'Median.Mass.Acc.MS2.Corrected',
       'MS2.Mass.Instability', 'Normalisation.Instability',
       'Median.RT.Prediction.Acc', 'Average.Peptide.Length',
       'Average.Peptide.Charge', 'Average.Missed.Tryptic.Cleavages', 'Group',
       'Filename', 'Subfolder', 'Root', 'Peptides.Identified', 'Organism',
       'Taxonomic ID (NCBI)', 'Database', 'Proteome_ID',
       'Strain_ID_Experiment', 'Strain_ID_UniProt', 'Total.Protein.Number.Ref',
       'Protein.Identification.Rate'],
      dtype='object')

## DIA --- Computational Visualization Across All Runs

In [12]:
dict_dia_charts = {
    'Retention_Time': {
        'Column_Name': 'FWHM.RT',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'MS1_Signal': {
        'Column_Name': 'MS1.Signal',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'MS2_Signal': {
        'Column_Name': 'MS2.Signal',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'MS1_Accuracy': {
        'Column_Name': 'Median.Mass.Acc.MS1',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'MS1_Accuracy_Corrected': {
        'Column_Name': 'Median.Mass.Acc.MS1.Corrected',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'MS2_Accuracy': {
        'Column_Name': 'Median.Mass.Acc.MS2',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'MS2_Accuracy_Corrected': {
        'Column_Name': 'Median.Mass.Acc.MS2.Corrected',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'Precursors_Identified': {
        'Column_Name': 'Precursors.Identified',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'Peptides.Identified': {
        'Column_Name': 'Peptides.Identified',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'Proteins_Identified': {
        'Column_Name': 'Proteins.Identified',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'MS2_Mass_Instability': {
        'Column_Name': 'MS2.Mass.Instability',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'Normalisation_Instability': {
        'Column_Name': 'Normalisation.Instability',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'Median_RT_Prediction_Accuracy': {
        'Column_Name': 'Median.RT.Prediction.Acc',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'Average_Peptide_Length': {
        'Column_Name': 'Average.Peptide.Length',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'Average_Peptide_Charge': {
        'Column_Name': 'Average.Peptide.Charge',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'Average_Missed_Tryptic_Cleavages': {
        'Column_Name': 'Average.Missed.Tryptic.Cleavages',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'Protein_Identification_Rate': {
        'Column_Name': 'Protein.Identification.Rate',
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None,
            'three_comparison': None,
            'four_comparison': None
        }
    },
    'MS1_Accuracy_Comparison': {
        'Column_Name': ['Median.Mass.Acc.MS1', 'Median.Mass.Acc.MS1.Corrected'],
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None
        }
    },
    'MS2_Accuracy_Comparison': {
        'Column_Name': ['Median.Mass.Acc.MS2', 'Median.Mass.Acc.MS2.Corrected'],
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None
        }
    },
    'Peak_Analysis': {
        'Column_Name': ["FWHM.RT", "Total.Quantity"],
        'Charts': {
            '100SPD': None,
            '200SPD': None,
            '500SPD': None,
            'all': None
        }
    },
}

dict_dia_configs = {
    '100SPD': {
        'color': _STRING_COLOR_DIA100SPD,
        'color_strong': _STRING_COLOR_DIA100SPD_STRONG,
        'path': _PATH_DIA_100SPD,
    },
    '200SPD': {
        'color': _STRING_COLOR_DIA200SPD,
        'color_strong': _STRING_COLOR_DIA200SPD_STRONG,
        'path': _PATH_DIA_200SPD,
    },
    '500SPD': {
        'color': _STRING_COLOR_DIA500SPD,
        'color_strong': _STRING_COLOR_DIA500SPD_STRONG,
        'path': _PATH_DIA_500SPD,
    },
    'all': {
        'color': _STRING_COLOR_DIAall,
        'color_strong': _STRING_COLOR_DIAall_STRONG,
        'path': _PATH_DIA_ALL_RUNS,
    }
}

In [13]:
for string_feature in dict_dia_charts.keys():

    chart_dia_three_config_comparison = go.Figure()
    chart_dia_four_config_comparison = go.Figure()

    for string_configuration in dict_dia_configs.keys():

        df_dia = pd.read_csv(
            dict_dia_configs[string_configuration]['path'], delimiter='\t')
        chart_dia = go.Figure()

        if string_feature in ["MS1_Accuracy_Comparison", "MS2_Accuracy_Comparison"]:
            chart_dia.add_trace(
                go.Violin(
                    x=["value"] * len(df_dia),
                    y=df_dia[dict_dia_charts[string_feature]["Column_Name"][0]],
                    name=dict_dia_charts[string_feature]["Column_Name"][0],
                    box_visible=True,
                    points="all",
                    pointpos=-1.2,      # points to the left
                    jitter=0.05,
                    side="negative",
                    line_color=dict_dia_configs[string_configuration]['color'],
                    marker_color=dict_dia_configs[string_configuration]['color']
                )
            )

            chart_dia.add_trace(
                go.Violin(
                    x=["value"] * len(df_dia),
                    y=df_dia[dict_dia_charts[string_feature]["Column_Name"][1]],
                    name=dict_dia_charts[string_feature]["Column_Name"][1],
                    box_visible=True,
                    points="all",
                    pointpos=1.2,      # points to the right
                    jitter=0.05,
                    side="positive",
                    line_color=dict_dia_configs[string_configuration]['color_strong'],
                    marker_color=dict_dia_configs[string_configuration]['color_strong']
                )
            )

            chart_dia.update_layout(
                violinmode="overlay",
                violingap=0,
                height=500,
                width=700,
                margin=dict(l=80, r=20, t=20, b=80),
                legend=dict(
                    orientation="h",
                    yanchor="bottom",
                    y=1.02,
                    xanchor="right",
                    x=1)
            )
            chart_dia.update_yaxes(title=dict(text=string_feature, font=dict(size=30)),
            tickfont=dict(size=25), showgrid=True)
            chart_dia.update_xaxes(
                showticklabels=False, ticks="", showline=True,
                tickfont=dict(size=25))

        elif string_feature == 'Peak_Analysis':
            chart_dia.add_trace(
                go.Scatter(
                    x=df_dia["FWHM.RT"], y=df_dia["Total.Quantity"],
                    mode='markers'
                )
            )
            chart_dia.update_traces(
                line_color=dict_dia_configs[string_configuration]['color'],
                marker_color=dict_dia_configs[string_configuration]['color'])

            chart_dia.update_xaxes(showgrid=True,
                title=dict(font=dict(size=30)), tickfont=dict(size=25))
            chart_dia.update_yaxes(showgrid=True,
                title=dict(font=dict(size=30)), tickfont=dict(size=25))
            chart_dia.update_layout(
                margin=dict(l=80, r=20, t=20, b=80))

        else:
            chart_dia.add_trace(
                go.Violin(
                    x=["value"] * len(df_dia),
                    y=df_dia[dict_dia_charts[string_feature]["Column_Name"]],
                    name=dict_dia_charts[string_feature]["Column_Name"],
                    box_visible=True,
                    points="all",
                    line_color=dict_dia_configs[string_configuration]['color'],
                    marker_color=dict_dia_configs[string_configuration]['color']
                )
            )

            chart_dia.update_xaxes(
                showticklabels=False, ticks="", showline=True,
                tickfont=dict(size=25))
            chart_dia.update_yaxes(
                showgrid=True,
                title=dict(text=dict_dia_charts[string_feature]["Column_Name"],
                    font=dict(size=30)),
                tickfont=dict(size=25))
            chart_dia.update_layout(
                margin=dict(l=80, r=20, t=20, b=80))

            # We also build a chart that compares a single feature across
            # either three or four configurations (100SPD, 200SPD, ...).
            # We do this only for singular features, and not feature
            # combinations that create more advanced plots
            if string_configuration != 'all':
                chart_dia_three_config_comparison.add_trace(
                    go.Violin(
                        x=[string_configuration]*len(
                            df_dia[dict_dia_charts[string_feature]["Column_Name"]]),
                        y=df_dia[dict_dia_charts[string_feature]["Column_Name"]],
                        name=dict_dia_charts[string_feature]["Column_Name"],
                        box_visible=True,
                        points="all",
                        line_color=dict_dia_configs[string_configuration]['color'],
                        marker_color=dict_dia_configs[string_configuration]['color']
                    )
                )

            chart_dia_four_config_comparison.add_trace(
                go.Violin(
                    x=[string_configuration]*len(
                        df_dia[dict_dia_charts[string_feature]["Column_Name"]]),
                    y=df_dia[dict_dia_charts[string_feature]["Column_Name"]],
                    name=dict_dia_charts[string_feature]["Column_Name"],
                    box_visible=True,
                    points="all",
                    line_color=dict_dia_configs[string_configuration]['color'],
                    marker_color=dict_dia_configs[string_configuration]['color']
                )
            )

        # We check if the four comparison figure is empty or not
        if chart_dia_three_config_comparison.data != tuple():
            chart_dia_three_config_comparison.update_yaxes(
                showgrid=True,
                title=dict(text=dict_dia_charts[string_feature]["Column_Name"],
                    font=dict(size=30)),
                tickfont=dict(size=25))
            chart_dia_three_config_comparison.update_xaxes(
                tickfont=dict(size=25))
            chart_dia_three_config_comparison.update_layout(
                margin=dict(l=80, r=20, t=20, b=80),
                violingap=0.5,
                height=500,
                width=800,
                showlegend=False)

            chart_dia_three_config_comparison.write_image(
                os.path.join(
                    _PATH_RESULTS_DIA_PDF,
                    "DIA_Three_Config_Comparison_" + string_feature + ".pdf"))
            chart_dia_three_config_comparison.write_html(
                os.path.join(
                    _PATH_RESULTS_DIA_HTML,
                    "DIA_Three_Config_Comparison_" + string_feature + ".html"))
            dict_dia_charts[string_feature]["Charts"][
                'three_comparison'] = chart_dia_three_config_comparison

        # We check if the four comparison figure is empty or not
        if chart_dia_four_config_comparison.data != tuple():
            chart_dia_four_config_comparison.update_yaxes(
                showgrid=True,
                title=dict(text=dict_dia_charts[string_feature]["Column_Name"],
                    font=dict(size=30)),
                tickfont=dict(size=25))
            chart_dia_four_config_comparison.update_xaxes(
                tickfont=dict(size=25))
            chart_dia_four_config_comparison.update_layout(
                margin=dict(l=80, r=20, t=20, b=80),
                violingap=0.5,
                height=500,
                width=1000,
                showlegend=False)

            chart_dia_four_config_comparison.write_image(
                os.path.join(
                    _PATH_RESULTS_DIA_PDF,
                    "DIA_Four_Config_Comparison_" + string_feature + ".pdf"))
            chart_dia_four_config_comparison.write_html(
                os.path.join(
                    _PATH_RESULTS_DIA_HTML,
                    "DIA_Four_Config_Comparison_" + string_feature + ".html"))
            dict_dia_charts[string_feature]["Charts"][
                'four_comparison'] = chart_dia_four_config_comparison

        chart_dia.write_image(
            os.path.join(
                _PATH_RESULTS_DIA_PDF,
                "DIA_" + string_configuration + "_" + string_feature + ".pdf"))
        chart_dia.write_html(
            os.path.join(
                _PATH_RESULTS_DIA_HTML,
                "DIA_" + string_configuration + "_" + string_feature + ".html"))

        dict_dia_charts[string_feature]["Charts"][string_configuration] = chart_dia

Resorting to unclean kill browser.
Resorting to unclean kill browser.

In [14]:
# =====================================================================
# Comparison: 100SPD-DIA vs 100SPD-DDA identification metrics
# One paired-violin figure per metric, in the same style as the
# three-config DIA comparison plots.
# =====================================================================

# Load the two 100SPD tables. df_dda is already in memory from the DDA
# block; we (re)load the 100SPD DIA table explicitly to be self-contained.
df_dia_100spd = pd.read_csv(dict_dia_configs['100SPD']['path'], delimiter='\t')

# Metric -> (DIA column, DDA column) for the genuinely comparable counts.
# All four are reported per run; DIA uses DIA-NN column names, DDA uses
# the FragPipe/QC column names.
dict_dia_dda_comparison = {
    'Precursors_Identified': {
        'dia_col': 'Precursors.Identified',
        'dda_col': 'Identified_precursors',
    },
    'Peptides_Identified': {
        'dia_col': 'Peptides.Identified',
        'dda_col': 'Identified_peptides',
    },
    'Proteins_Identified': {
        'dia_col': 'Proteins.Identified',
        'dda_col': 'Identified_proteins',
    },
    'Protein_Identification_Rate': {
        'dia_col': 'Protein.Identification.Rate',
        'dda_col': 'Protein.Identification.Rate',
    },
}

# x-axis group label -> (dataframe, column-key, color) is resolved per metric.
dict_comparison_modes = {
    '100SPD-DIA': {
        'df': df_dia_100spd,
        'color': _STRING_COLOR_DIA100SPD,
    },
    '100SPD-DDA': {
        'df': df_dda,
        'color': _STRING_COLOR_DARK_GREY,
    },
}

for string_feature in dict_dia_dda_comparison.keys():
    print(string_feature)

    chart_dia_dda_comparison = go.Figure()

    for string_mode in dict_comparison_modes.keys():

        df_mode = dict_comparison_modes[string_mode]['df']

        # pick the right column name for this mode
        if string_mode == '100SPD-DIA':
            column_name = dict_dia_dda_comparison[string_feature]['dia_col']
        else:
            column_name = dict_dia_dda_comparison[string_feature]['dda_col']

        chart_dia_dda_comparison.add_trace(
            go.Violin(
                x=[string_mode] * len(df_mode[column_name]),
                y=df_mode[column_name],
                name=string_mode,
                box_visible=True,
                points="all",
                line_color=dict_comparison_modes[string_mode]['color'],
                marker_color=dict_comparison_modes[string_mode]['color']
            )
        )

    chart_dia_dda_comparison.update_yaxes(
        showgrid=True,
        title=dict(text=string_feature, font=dict(size=30)),
        tickfont=dict(size=25))
    chart_dia_dda_comparison.update_xaxes(
        tickfont=dict(size=25))
    chart_dia_dda_comparison.update_layout(
        margin=dict(l=80, r=20, t=20, b=80),
        violingap=0.5,
        height=500,
        width=800,
        showlegend=False)

    chart_dia_dda_comparison.write_image(
        os.path.join(
            _PATH_RESULTS_DIA_PDF,
            "DIA_DDA_100SPD_Comparison_" + string_feature + ".pdf"))
    chart_dia_dda_comparison.write_html(
        os.path.join(
            _PATH_RESULTS_DIA_HTML,
            "DIA_DDA_100SPD_Comparison_" + string_feature + ".html"))

Precursors_Identified
Peptides_Identified
Proteins_Identified
Protein_Identification_Rate